import fs from "node:fs";
import path from "node:path";
import { resolveConfigPath } from "./store.js";

const loadedEnvFiles = new Set<string>();

function resolveEnvFilePath(configPath?: string): string {
  return path.resolve(path.dirname(resolveConfigPath(configPath)), ".env");
}

function parseEnvFile(contents: string): Record<string, string> {
  const entries: Record<string, string> = {};
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eqIndex = line.indexOf("=");
    if (eqIndex <= 0) continue;
    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    entries[key] = value;
  }
  return entries;
}

function renderEnvFile(entries: Record<string, string>): string {
  return [
    "# OwnLab environment variables",
    "# Generated by OwnLab CLI commands",
    ...Object.entries(entries).map(([key, value]) => `${key}=${JSON.stringify(value)}`),
    "",
  ].join("\n");
}

export function resolveOwnlabEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function readOwnlabEnvEntries(filePath = resolveEnvFilePath()): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return parseEnvFile(fs.readFileSync(filePath, "utf8"));
}

export function writeOwnlabEnvEntries(entries: Record<string, string>, filePath = resolveEnvFilePath()): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, renderEnvFile(entries), { mode: 0o600 });
}

export function mergeOwnlabEnvEntries(
  entries: Record<string, string>,
  filePath = resolveEnvFilePath(),
): Record<string, string> {
  const current = readOwnlabEnvEntries(filePath);
  const next = {
    ...current,
    ...Object.fromEntries(
      Object.entries(entries).filter(([, value]) => typeof value === "string" && value.trim().length > 0),
    ),
  };
  writeOwnlabEnvEntries(next, filePath);
  return next;
}

export function loadOwnlabEnvFile(configPath?: string): void {
  const filePath = resolveEnvFilePath(configPath);
  if (loadedEnvFiles.has(filePath) || !fs.existsSync(filePath)) return;
  loadedEnvFiles.add(filePath);
  const entries = readOwnlabEnvEntries(filePath);
  for (const [key, value] of Object.entries(entries)) {
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}
